phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building website..."
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync ./src s3://clearsky-static-website --delete
      - echo "Deployment successful."

artifacts:
  files:
    - "**/*"
